{% set name = "cdat_info" %}
{% set version = "2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://github.com/UV-CDAT/cdat_info/archive/2.10.tar.gz
    sha256: dcd32606f3947bb89c2d035dd869e47588c269212ca8b9278026365dde01a05b

build:
  number: 2
  skip: True  # [win or py3k]

requirements:
  build:
    - python
    - setuptools
    - python
  run:
    - python

test:
  imports:
    - cdat_info

about:
  home:  http://uvcdat.llnl.gov
  license: CCLRC
  license_file: LEGAL.txt
  summary: 'Climate Data Analysis Tools'
  description: |                                                                                                                                             
    is a powerful and complete front-end to a rich set of visual-data 
    exploration and analysis capabilities well suited for climate-data 
    analysis problems.
  dev_url: http://github.com/UV-CDAT/cdms                                                                                                                    


extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
