{% set name = "cdat_info" %}
{% set version = "2.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    git_rev: {{ version }}
    git_url: git://github.com/UV-CDAT/uvcdat.git

build:
  number: 0
  skip: True  # [win]
  # noarch_python: True

requirements:
  build:
    - python
    - setuptools
    - python <3 
  run:
    - python <3 

test:
  imports:
    - cdat_info

about:
  home:  http://uvcdat.llnl.gov
  license: CCLRC
  license_file: LEGAL.txt
  summary: 'Climate Data Analysis Tools'
  description: |                                                                                                                                             
    is a powerful and complete front-end to a rich set of visual-data 
    exploration and analysis capabilities well suited for climate-data 
    analysis problems.
  dev_url: http://github.com/UV-CDAT/cdms                                                                                                                    


extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
