{% set name = "cdat_info" %}
{% set version = "2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://github.com/UV-CDAT/cdat_info/archive/2.12.tar.gz
    sha256: 5a62668c39703315f8599002056d29c0fa8223c60ca9748631693c39383ce7b2

build:
  number: 1
  skip: True  # [win]
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - python
  run:
    - python
    - requests

test:
  imports:
    - cdat_info

about:
  home:  http://uvcdat.llnl.gov
  license: CCLRC
  license_file: LEGAL.txt
  summary: 'Climate Data Analysis Tools'
  description: |                                                                                                                                             
    is a powerful and complete front-end to a rich set of visual-data 
    exploration and analysis capabilities well suited for climate-data 
    analysis problems.
  dev_url: http://github.com/UV-CDAT/cdms                                                                                                                    


extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
