{% set version = "8.1.1" %}
{% set actual_version = "8.1" %}

package:
  name: cdat_info
  version: {{ version }}

source:
    url: https://github.com/UV-CDAT/cdat_info/archive/v{{ actual_version }}.tar.gz
    sha256: c33a014aadcad566bda8a9def1642224997e3cfb180ff46a151fa8611a44de0f

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - nbformat

test:
  imports:
    - cdat_info

about:
  home:  http://cdat.llnl.gov
  license: BSD
  license_file: bsd-3-clause.txt
  summary: 'Climate Data Analysis Tools'
  description: |                                                                                                                                             
    is a powerful and complete front-end to a rich set of visual-data 
    exploration and analysis capabilities well suited for climate-data 
    analysis problems.
  dev_url: http://github.com/CDAT/cdat_info

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
